### ISSUE TITLE
Vault keys are not automatically deleted

### ISSUE THREAD

**Issue by byronicle** [hashicorp/vault-plugin-secrets-gcp#108]
Hi,

I expected my key to be deleted after 2 minutes, using default values. However, after two minutes it was not deleted.

I configured the gcp secrets engine with:
```
vault write gcp/config \ ttl=2m \ max_ttl=10m
```

I then requested a key using:
```
vault read -field="private_key_data" gcp/key/my-generic-key
```

I checked to see if it was deleted two minutes later, and it was not.

However, if I used `ttl=2m` in the key request, the key was deleted 2 minutes later.
```
vault read -field="private_key_data" gcp/key/my-generic-key ttl=2m
```

Vault v1.4.0

**Comment by raymonstah** [comment]
Hey @byronicle, we realize that this issue is almost 2 years old at this point, and the problem you mentioned may have been fixed since.

I've gone through the steps to reproduce the issue by setting a TTL and creating a `service_account_key`. After reading the key, the key then expires after the configured TTL. I wanted to point out that the [documentation](https://developer.hashicorp.com/vault/api-docs/secret/gcp#parameters) mentions that the TTL only applies for long-lived credentials such as service account keys.

Also, I wanted to point out that the path described in the issue `/gcp/key/:roleset` has been [deprecated](https://developer.hashicorp.com/vault/api-docs/secret/gcp#generate-secret-iam-service-account-creds-service-account-key) as of v1.12.

If you're still running into this issue on a more recent version of Vault, feel free to open another issue.
