### ISSUE TITLE
Problems Creating Static Accounts After Upgrading to 1.9.0

### ISSUE THREAD

**Issue by dcb-imvaria** [hashicorp/vault-plugin-secrets-gcp#128]
I just upgraded our vault server to 1.9.0 from 1.8.3.  When attempting to create a new static-account with secret_type="service_account_key", I get the following error:

    Code: 403. Errors:

    * 1 error occurred:
	    * permission denied

`vault token capabilities gcp/static-account` yields the following:
create, delete, list, read, sudo, update

The results suggest that the permissions are adequate for creating a static-account.  I'm at a loss as to why the write command is failing.

**Comment by robmonte** [comment]
@dcb-imvaria Hello! First I wanted to apologize for the delayed response to your issue here. I wanted to let you know that we reserve Github issues for bug reports and feature requests. That being said, perhaps you've solved this issue some time ago already; if you haven't, or if you have new issues in the future, please check out our [Vault forum & discussion platform](https://discuss.hashicorp.com/c/vault/30) for questions about using Vault. Thank you!
