### ISSUE TITLE
Service Account key being revoked after 768h when configured to last 30y

### ISSUE THREAD

**Issue by onetwopunch** [hashicorp/vault-plugin-secrets-gcp#141]
I'm using the Terraform provider for Vault but I don't believe this should affect anything. I have the following configuration for the  particular backend that needs service accounts for apps with long-lived creds (vault is the only thing that we've given permission to cross an air-gap boundary for stuff like this so I can't just download the SA key). 

```hcl
locals {
  # 30 years
  forever = 946080000
  apps = {
    app1 = {
      email = "app1@project-id.iam.gserviceaccount.com"
      owner = "username"
    }
  }
}

# This backend is for apps and thus SA keys must be long-lived
# which is generally ok since they will ideally have lower perms
# than humans
resource "vault_gcp_secret_backend" "gcp_app_identity" {
  path                      = "gcp_app_identity"
  max_lease_ttl_seconds     = local.forever
  default_lease_ttl_seconds = local.forever
}

resource "vault_gcp_secret_static_account" "app" {
  for_each = local.apps

  backend               = vault_gcp_secret_backend.gcp_app_identity.path
  static_account        = each.key
  secret_type           = "service_account_key"
  service_account_email = each.value.email
  token_scopes          = ["https://www.googleapis.com/auth/cloud-platform"]
}
```

What I've seen happen twice now is that we have an app that was configured with the above and generated a lease, where I was able to verify the duration to be 30 years, and yet at exactly 768 hours from the secret creation, the secret is revoked (i.e. key is deleted). 

We currently have 2 apps using this mechanism. The one that was deleted today had a very similar output only a week ago as this one, which we've also generated. So I know that the lease is set correctly, but yet the secret keeps getting revoked.

```
$ vault lease lookup gcp_app_identity/static-account/app1/key/Ybjn0vp0ekJXb5o0vV2FUwGN
Key             Value
---             -----
expire_time     2052-05-14T18:18:42.689600107-07:00
id              gcp_app_identity/static-account/app1/key/Ybjn0vp0ekJXb5o0vV2FUwGN
issue_time      2022-05-22T18:18:42.689599876-07:00
last_renewal    <nil>
renewable       true
ttl             262515h17m30s
```

I need to know if there's something in my configuration that broken or if there's a default value that's not being overridden when it should be.

Any help here would be appreciated. This is flying in the face of everything I thought I knew about how Vault works 😞

**Comment by kalafut** [comment]
Thanks for the report @onetwopunch. Which version of Vault are you using?

**Comment by onetwopunch** [comment]
@kalafut thanks for the quick response. We're using 1.8.0 currently

**Comment by ljupchokotev** [comment]
Looks similar to https://github.com/hashicorp/vault/issues/10443. I believe the root cause is that the token which generated the keys has expired, so the keys also expire with it. I am very curious how you would create longer living keys without the need to use a token to authenticate to Vault which has an even longer TTL than the key.

**Comment by onetwopunch** [comment]
@ljupchokotev Is this true across all dynamic key providers in Vault or just GCP? That does line up logically with the behavior we're seeing but I can't seem to find that documented anywhere.

**Comment by ljupchokotev** [comment]
> @ljupchokotev Is this true across all dynamic key providers in Vault or just GCP? That does line up logically with the behavior we're seeing but I can't seem to find that documented anywhere.

I have not tried any other secret engine but at least we are seeing this behavior for GCP. I was not able to find anything in the documentation either.

**Comment by onetwopunch** [comment]
@kalafut any thoughts on this?

**Comment by ljupchokotev** [comment]
@onetwopunch, after talking with HashiCorp support, they confirmed that when the token which creates the dynamic secret expires, the dynamic secret expires with it. This should be the same behavior for all dynamic secret engines.

> All dynamic secret leases are tied to the token that generates the secret. When that token expires, any leases created with that token are also revoked - regardless of the secret’s lease TTL.

I am still waiting to get an answer on whether the lease duration should show the actual correct TTL i.e. that of the token in this case since it's shorter.

To get a long living key, you would also need to use a long living token to generate it. Or, you can use periodic tokens which you can renew before they expire so that the key doesn't expire.

**Comment by robmonte** [comment]
Hi @onetwopunch 
I have been looking into and recreating this issue. I noticed when I manually configure the GCP secrets engine via CLI, it recognizes the cap of 768h on the service account key when using any TTL above that value. So far I have only been able to successfully recreate a TTL above that limit when using the Terraform provider based on the plan you gave.

I wanted to ask you if you encountered this problem without Terraform? Your initial post seems to indicate that you don't believe Terraform is necessary to encounter this problem or was it was an assumption?

&nbsp;

Also hi @ljupchokotev 
I looked at the related issue you linked where you also encountered this problem with approle auth. I was able to successfully recreate the issue using a short-lived approle login. In this case, i at least still seems to recognize the 768h limit on the lease, unlike the Terraform method where it shows a lease of 200,000+ hours. However, I recognize that the 768h lease is still inaccurate.

**Comment by robmonte** [comment]
I wanted to post a second update for this. Regarding the use of Terraform for GCP secrets engine, we discovered somewhat of a bug where the provider was only setting the provided TTL to the backend mount but not on the engine config itself. Having a TTL on the engine config is a unique feature that I believe only GCP secrets has, which may be why it was missed.

Additionally, the implicit 768h TTL being enforced on these tokens may be due to Vault's default system TTLs. To overwrite this, you'd need to specify `default_lease_ttl` and/or `max_lease_ttl` values in Vault's main configuration, [(documentation here for reference)](https://developer.hashicorp.com/vault/docs/configuration#default_lease_ttl).

&nbsp;

As for the overarching topic of "inaccurate" TTLs, particularly regarding an auth-enforced TTL on a token generated under it: \
We have started internal discussions for how we may address this in the future. I can't provide any estimates on timeline, but we acknowledge the confusion and error-prone behavior that may arise from Vault providing the users with a TTL that appears longer than may be true. It gets complex when you consider than an auth login's TTL may be extended by renewing, which by proxy would extend the lifetime of tokens generated under it. These complexities will need to be considered.

Thank you for raising awareness of these issues with us!

**Comment by robmonte** [comment]
Hi again!

I wanted to give a final update here. I am fairly confident at this point there is no secondary issue with the GCP Secret engine causing secret leases to expire earlier than expected. This perceived issue is what ljupchokotev referenced, where the Vault token creating the lease is expiring which revokes any leases under it.

I am going to mark this issue resolved as this is expected behavior. In the short term, we will update the documentation to try explaining the token's relationship with lease revocation better. I will also make a task for us internally to consider updating the lease logic to reflect a token's limits - to be prioritized at a later time.
