### ISSUE TITLE
Roleset bindings should support BigQuery datasets

### ISSUE THREAD

**Issue by cschroer** [hashicorp/vault-plugin-secrets-gcp#24]
It is not possible to add bindings for a bigquery dataset resource.

Looks like the big query api does not provide `getIamPolicy`, `setIamPolicy` and `testIamPermissions`. See [update](https://cloud.google.com/bigquery/docs/reference/rest/v2/datasets/update) for [datasets](https://cloud.google.com/bigquery/docs/reference/rest/v2/#Datasets)

Is there any chance to add support for datasets, too?

**Comment by ondrejklucka** [comment]
Hi Emily, recently we had a similar need. Brief look onto the plugin suggests it'd require the following:

- Create a 2nd (completely different and BQ-specific) way of handling access control
- Use get/patch methods to configure access list on datasets/tables (patch in a read-modify-write cycle)

More specifically:

- create vault-plugin-secrets-gcp/plugin/bqutil/* that supports BQ specific resources/handlers
- create access list bindings in vault-plugin-secrets-gcp/plugin/util/
- extend vault-plugin-secrets-gcp/plugin/[backend.go & role_set.go & path_role_set.go] with access-list specific policy

Any way I can help with this?

**Comment by cschroer** [comment]
Hey @emilymye 

did you had a chance to look at it?

Best regards
Chris

**Comment by emilymye** [comment]
@cschroer I have not yet, sorry! I'm not sure I'll get a chance this quarter - if you need it urgently, I'm happy to review community contributions :)

**Comment by onetwopunch** [comment]
@emilymye I'm happy to start looking into fixing this now as I have a customer with an urgent need to dynamically create Service Accounts that are provisioned with access to BigQuery. Any leads so far so as not to waste any effort you've already put into thinking about this?

**Comment by emilymye** [comment]
@onetwopunch sorry for long delay in response! If you haven't gotten around to it, I might try to get this done next quarter, but otherwise go for it :) I haven't really had the time to think about this too hard, but I'd say the easiest thing would be to implement a BigQuery-specific [IamResource](https://github.com/hashicorp/vault-plugin-secrets-gcp/blob/master/plugin/iamutil/iam_resource.go#L15) and add it somewhere in the iamutil folder. Then, generate a new map or add the custom resource to the autogenerated one:

https://github.com/hashicorp/vault-plugin-secrets-gcp/blob/4a8176eeed35e428f9297c1dab3cda2d097ec201/plugin/iamutil/iam_resources_generated.go#L4-L6

We could honestly move ^ out of the autogenerated file, so it'd be easier to add custom files.

If you wrap it in a new value, make sure to change the reference here: https://github.com/hashicorp/vault-plugin-secrets-gcp/blob/4a8176eeed35e428f9297c1dab3cda2d097ec201/plugin/backend.go#L52

**Comment by petersonnek** [comment]
Has any progress been made on this? We could definitely use the BQ integration as well.

**Comment by onetwopunch** [comment]
Starting work on this today. Should have a PR up in the next few days. I think the cleanest way of going about this is to add an entry for BigQuery into the resource list in [generate_iam.go](https://github.com/hashicorp/vault-plugin-secrets-gcp/blob/master/plugin/iamutil/internal/generate_iam.go) and make an exception for datasets in the [SetIamPolicyRequest](https://github.com/hashicorp/vault-plugin-secrets-gcp/blob/master/plugin/iamutil/iam_resource.go#L63) function such that the request a PATCH with  an access object for each "binding".
