### ISSUE TITLE
Full bucket resource aka. `//storage.googleapis.com/{bucket}` doesn't work.

### ISSUE THREAD

**Issue by jozuenoon** [hashicorp/vault-plugin-secrets-gcp#26]
I'm getting this:
```
error parsing relative resource path in full resource name '//storage.googleapis.com/{my-bucket}': invalid relative resource name {my-bucket} (too few tokens)"
```
Provided that full resource name is specified this way here: https://cloud.google.com/resource-manager/docs/cloud-asset-inventory/resource-name-format 

It seems that we could only reference storage resource with `buckets` and not with `Full resource name` which is `//storage.googleapis.com/{bucket}` so I'm bit confused as documentation allows referencing with full resource names. 

*After some code browsing:*
As I can see in code it would work with `//storage.googleapis.com/buckets/{bucket}` ?

**Comment by emilymye** [comment]
Yup! I generated the IAM code to stick with the [API definition of full resource name](https://cloud.google.com/apis/design/resource_names#full_resource_name). I'm not sure why Cloud Asset decided to do that instead of  //storage.googleapis.com/buckets/{bucket} (or //storage.googleapis.com/b/{bucket} which is sad but actually how the storage API looks). Storage has always been a snowflake though, so it's bound to cause confusion at some layer. Sorry for the confusion!
