### ISSUE TITLE
Unable to create a Roleset binding for a GKE cluster resource

### ISSUE THREAD

**Issue by soorena776** [hashicorp/vault-plugin-secrets-gcp#64]
I am following the instructions given [here](https://www.vaultproject.io/docs/secrets/gcp/index.html#roleset-bindings) to bind an IAM role for my GKE cluster resource, with following selfLink: 
```yaml
selfLink: https://container.googleapis.com/v1/projects/my-project/locations/us-central1/clusters/my-cluster
```

For this purpose I run the following command: 
```bash
vault write gcp_test/roleset/k8s-token \
    project="my-project" \
    secret_type="access_token"  \
    token_scopes="https://www.googleapis.com/auth/cloud-platform" \
    bindings=-<<EOF
      resource "https://container.googleapis.com/v1/projects/my-project/locations/us-central1/clusters/my-cluster" {
        roles = ["roles/container.admin","roles/iam.serviceAccountUser","roles/compute.networkAdmin"]
      }
EOF
```

However, I'm getting the following error:

```bash
Error writing data to gcp_test/roleset/k8s-token: Error making API request.

URL: PUT http://<vault-ip>:8200/v1/gcp_test/roleset/k8s-token
Code: 400. Errors:

* invalid resource "https://container.googleapis.com/v1/projects/my-project/locations/us-central1/clusters/my-cluster": unsupported resource type: projects/locations/clusters
```

I followed the documentation provided [here](https://github.com/hashicorp/vault-plugin-secrets-gcp#auto-generated-iam-config) but couldn't find any entry for this selflink. 

Are GKE clusters not supported as resources?

**Comment by emilymye** [comment]
Nope! In general, we can currently only support setting Cloud IAM policies if the [resource](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters) supports `get/setIamPolicy()`, which is considered the cross-resource "IAM API methods". GKE is a weird API because it allows both IAM and k8s RBAC to set permissions. From what I recall ([docs](https://cloud.google.com/kubernetes-engine/docs/how-to/iam)), GKE only allow setting IAM policies at the project level.

**Comment by soorena776** [comment]
Thanks for the prompt response!

As you pointed out setting the resource to project (e.g. `//cloudresourcemanager.googleapis.com/projects/my-project`) works, but then it defeats the purpose of `resource` field, as it targets all the resources in the project rather than a specific one.

**Comment by emilymye** [comment]
Yes, this is a limitation of the API itself. I think rather than trying to set the correct permissions at a project-level, GKE permissions are intended to be 1) cloud IAM to give service accounts or users basic access to GKE clusters and 2) k8s RBAC for setting permissions at a lower granularity (e.g. across namespaces). For example, you can give a service account read-only access to clusters (all clusters in a project, because Cloud IAM limitations), and then edit write access for namespaces using RBAC. This does limit the capabilities of this plugin specifically for GKE, since Vault owns the service account and can change its name. We are working on some features to allow you to specify an account name to create/use permissions for, which might work better.

I'm going to go ahead and close this issue, but feel free to re-open if you have more questions!
